### ISSUE TITLE
Both links are down

### ISSUE THREAD

**Issue by chrisbinsunny** [amith-vp/ktunotificationapi#2]
Both of the links are down right now. Any ways to host it back?

**Comment by amith-vp** [comment]
Thank you for bringing this to my attention. I apologize for any inconvenience.  Heroku credits got exhausted . I will work on resolving the issue and providing a new domain/IP as soon as possible. By tomorrow possibly

**Comment by amith-vp** [comment]
changed to render
https://ktuapi.onrender.com

**Comment by chrisbinsunny** [comment]
Thank you so much for the quick response. It would be great if you add a doc on how to host it on our own servers or domains. Like what is the starting point or where to point to? 
Again, Thank you

**Comment by amith-vp** [comment]
You must have node js installed.  Download the repo. cd into directory then 
`npm i`
`node app.js`
Server should start on localhost:3000
